---
title: "Multi-level Modelle -- Woche 1 -- 24.10.2022"
---

$$
\begin{aligned}
y_{i, j, k} &=\beta_0+S_{0, i}+\beta_\delta X_{i, j, k}+\epsilon_{i, j, k}, \\
i &=1, 2, \ldots, I \quad j=1,2, \ldots, J \quad k=1,2 \\
\boldsymbol{\epsilon} & \sim \mathcal{N}\left(0, \sigma_\epsilon^2\right) \\
\boldsymbol{S}_{\mathbf{0}} & \sim \mathcal{N}\left(0, \sigma_{S_0}^2\right)
\end{aligned}
$$

## Leitung

[José C. García Alanis](https://methoden.amd.psychologie.uni-mainz.de/jose-c-garcia-alanis/)\
Abteilung für Analyse und Modellierung komplexer Daten\
Wallstraße 3, Raum 06-255\
D-55122 Mainz\
[jose.alanis at uni-mainz.de](jose.alanis@uni-mainz.de)\

## Organisatorisches und wichtige Infos
- Terminübersicht, Kurs-Ressourcen, wichtige Links.

### Allgemeine Materialien für das Seminar
- Wichtige Informationen und Kursmaterialien werden auf die LMS/Moodle-Seite des Seminars veröffentlicht:
  - [Link zum Seminar](https://lms.uni-mainz.de/moodle/course/view.php?id=71232) auf LMS.
    - **Wann**: Montags von **10:15** - **11:45** Uhr (24.10.22 - Mo. 06.02.23).
    - **Wo**: CIP-Pool im Psychologischen Institut -- [01 236 PC-Pool](https://jogustine.uni-mainz.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-AIOuHkVQ-ZVOjaPFTSfJe0fWlfmTT0A1QeOGKc8ZcN7tBv79jS4wxZtNFDc1yDFR8PiBb0hmkt-mTiTdZ-MGTwvOPNjKCUy5M59I~10o84KsqUzsszoSCI~kitRtJz2dP7MVJphBuVPb8HzLqaLF2VIpq5F0ssgOIbJPvqj6C7Jl-Hns_)

## Inhalt des Seminars

**Multi-Level Modelle** (auch Mehrebenen-Modelle genannt) ermöglichen es, Daten zu analysieren, die sich hierarchisch übergeordneten Einheiten zuordnen lassen. Hier wird häufig von *genesteten* oder *hierarchisch strukturierten/organisierten Daten* gesprochen. Beispiele dafür sind Kinder, die unterschiedlichen Familien angehören, Mitarbeiter:innen verschiedener Abteilungen oder Patient:innen von unterschiedlichen Therapeut:innen oder Kliniken. Diese Gruppen haben alle eine Gemeinsamkeit: Ihre Mitglieder:innen lassen sich eindeutig einer Gruppe (und nur einer Gruppe) zuordnen.

Ein typisches Merkmal von hierarchisch strukturieren Daten ist, dass Daten innerhalb einer Gruppe ähnlicher zueinander sind als zu Daten anderer Gruppen. Dadurch ergeben sich häufig Unterschiede, die auf die Zugehörigkeit zu einer jeweiligen Gruppe zurückzuführen sind (z.B. unterschiedliche Therapieverläufe für unterschiedliche Störungsgruppen oder Performanzunterschiede zwischen Abteilungen).

Ein Vorteil von Multi-Level Modelle ist, dass sie die obengenannten Ählichkeitsmuster in hierarchisch organisierten Daten berücksichtigen. Somit können sie dafür eingesetzt werden, genauere und realitätsnähere Aussagen über den Effekt einer Maßnahme oder über die Beziehung zwischen Prädiktoren und Outcomes zu treffen. Am Ende des Seminars sollten Sie folgende Fragen beantworten können: Was sind hierarchisch strukturierte Daten und wie können diese erkannt werden? Welche Konsequenzen (in Sinne einer Modellspezifikation) bringen hierarchisch strukturierte Daten mit sich? Wie können Multi-Level Modelle in R spezifiziert werden und welche Arten von Modellen gibt es? Wie sind die Ergebnisse eines Multilevel-Modells zu interpretieren?

## Begleitendes Tutorium

Das Seminar wird von einem Softwaretutorium begleitet, in dem Sie die Grundlagen des Umgangs mit der **Statistiksoftware R** sowie die Datenaufbereitung im *tidyverse* erlernen und einüben sollen. Aufbauend auf diesen Grundkenntnissen werden im Tutorium die Inhalte dieses Seminars besprochen und vertieft. D.h. das Tutorium behandelt explizit, die Inhalte des Seminars und ist im Besonderen für dieses Seminar konzipiert. Bitte melden Sie sich daher auch für das begleitende Tutorium an!
Der erste Termin des Tutoriums am ist am 31.10.22. Das Tutorium findet während der ersten Hälfte des Semesters wöchentlich statt. Melden Sie sich bitte unbedingt vor der ersten Lehrveranstaltung selbstständig mit dem Passwort **bunsen** für den LMS-Kurs des Tutoriums an:

- [Link zum Tutorium](https://lms.uni-mainz.de/moodle/user/index.php?id=71758) auf LMS.

Wir eine Reihe von Materialien zusammengestellt, um Ihnen den Einstieg in die Programmiersprache R zur erleichtern. Diese können Sie unter dem folgenden Link erreichen:

- **R-Kurs-Buch** von der Abteilung Analyse und Modellierung komplexer Daten: https://amd-lab.github.io/R-Kurs-Buch/

## Terminübersicht

| Sitzung |     Datum     |      Inhalt         | Anmerkungen                                                   |
|:-------:|:-------------:|:-------------------:|:--------------------------------------------------------------|
|    1    | 24. Okt. 2022 | Organisatorisches   | ✍️ [Eingangs-Assessment](https://forms.gle/qQGjXxdMbs1fJrzi8)  |
|    2    | 31. Okt. 2022 | Hierarchische Daten |                                                           |
|    3    | 07. Nov. 2022 |                   |                                                           |
|    4    | 14. Nov. 2022 |                   |                                                           |
|    5    | 21. Nov. 2022 |                   |                                                           |
|    6    | 28. Nov. 2022 |                   |                                                           |
|    7    | 05. Dez. 2022 |                   |                                                           |
|    8    | 12. Dez. 2022 |                   |                                                           |
|    9    | 19. Dez. 2022 |                   |                                                           |
|    🎁   |      🏡        |        🎄         | Weihnachtspause                                           |
|   10    | 09. Jan. 2023 |                   |                                                           |
|   11    | 16. Jan. 2023 |                   |                                                           |
|   12    | 23. Jan. 2023 |                   |                                                           |
|   13    | 30. Jan. 2023 |                   |                                                           |
|   14    | 06. Feb. 2023 |                   |                                                           |
